### ISSUE TITLE
undefined method `paginate' error

### ISSUE THREAD

**Issue by TheR2** [kaminari/kaminari-mongoid#5]
Just updated to new kaminari and got this error.

I have replaced 'kaminari' with 'kaminari-mongoid' in gemfile und updated bundle.

Back to 0.17.0 for now.

by
TheR

**Comment by yuki24** [comment]
Thank you for reporting. I believe you'd just have to add the following to your Gemfile:

```ruby
gem 'kaminari-mongoid'
gem 'kaminari-actionview'
```

**Comment by shantilal-narola** [comment]
@yuki24 I stumbled upon this issue as well. I'd be great if you could update the `README` mentioning the same.
