### ISSUE TITLE
Incorrect count for paginated results

### ISSUE THREAD

**Issue by calin-ciobanu** [kaminari/kaminari-mongoid#8]
See below example:
```
#controller
@templates = Template.where(read_conditions).order_by(updated: :desc).page(params[:page]).per(params[:per_page]) # does not matter if per_page is supplied or nil
```

```
(byebug) @templates[5]
nil
(byebug) @templates.count
8
(byebug) @templates.entries.count
5
(byebug) @templates.entries.size
5
(byebug) @templates.class
Mongoid::Criteria
```
for `@templates[0]` .. `@templates[4]` there are values.

**Comment by yuki24** [comment]
Thanks for reporting! This also seems like a bug, I'll look into it once I have time.

**Comment by FunkyloverOne** [comment]
I just was testing if my app is vulnerable to this bug, and I wasn't able to reproduce it on mongoid 6.2.

**Comment by yuki24** [comment]
Right now I don't have enough bandwidth to look into this issue but will do in the first week of March. Thanks for bearing with us.

**Comment by Cakirucho** [comment]
Hi guys, currently i'm facing the same issue as @calin-ciobanu.

Running` mongoid  5`,  `kaminari 1.1.1` and `kaminari-mongoid 1.0.1`

Typing:

`users = User.all.page(1).per(5)`

```console
2.3.1 :012 > users.count
 => 246190 
2.3.1 :013 > users.entries.count
 => 5 
2.3.1 :014 > users.entries.size
 => 5 
2.3.1 :015 > users[5]
 => nil 
2.3.1 :016 > users.class
 => Mongoid::Criteria
```

**Comment by yuki24** [comment]
I'm surprized the `#count` method is designed that way. Given that it is intentional, I don't think there's anything we can do. Thanks all!
