### ISSUE TITLE
undefined local variable or method `default_per_page' for Profile:Class Did you mean? default_scope

### ISSUE THREAD

**Issue by DenniJensen** [kaminari/kaminari-mongoid#9]
After I updated kaminari I received an error for `Mongoid`. When I use the `kaminari-mongoid` gem I have the following issue.

`undefined local variable or method 'default_per_page' for Profile:Class Did you mean? default_scope`

![screen shot 2017-12-20 at 14 35 01](https://user-images.githubusercontent.com/3010752/34209579-fea917e8-e592-11e7-8866-54596b078b41.png)

I updated the version from `0.16.3` to `1.1.1`

**Comment by yuki24** [comment]
Interesting. It's the most basic feature of Kaminari and I have no idea why such a bug could slip in. Would you mind creating an example app that replicates your issue?

Thanks for reporting!

**Comment by DenniJensen** [comment]
Hey @yuki24,

I created a new [rails project](https://github.com/DenniJensen/testingKaminariMongoid) and `kaminari` works here for mongoid. 

I have to dig into my Project where I updated the version of kaminari from `0.16.3` to `1.1.1`. Maybe I did not configured it right or something is not loaded inside rails. 

If I find something when I will show it.

Thank you for your quick response.

**Comment by DenniJensen** [comment]
Do I need a specific version for mongoid here? Iam using mongoid version `5.2.1`

**Comment by noelrappin** [comment]
I am having the same error on Mongoid 4.0.2

**Comment by noelrappin** [comment]
[kaminari_sample.zip](https://github.com/kaminari/kaminari-mongoid/files/1579684/kaminari_sample.zip)

Here's a sample app that exhibits the behavior. It is a stock Rails 4.2.x that has added Mongoid and Kaminari-Mongoid to the gem file. There is one model, `Foo`. From my pry session:

~~~
> Foo.default_per_page
NoMethodError: undefined method `default_per_page' for Foo:Class

 Foo.ancestors
=> [Foo, Mongoid::Document, Kaminari::Mongoid::MongoidExtension::Document, Kaminari::ConfigurationMethods...]

 Foo.send(:include, Kaminari::ConfigurationMethods)
=> Foo
irb(main):004:0> Foo.default_per_page
=> 25

Foo.ancestors
=> [Foo, Mongoid::Document, Kaminari::Mongoid::MongoidExtension::Document, Kaminari::ConfigurationMethods...]
~~~

The ancestor list doesn't change. Is this some kind of load order issue?

**Comment by yuki24** [comment]
I'm not sure yet but this commit may be it: https://github.com/kaminari/kaminari/commit/4536cc2800a40fcd91c0f4678133e4e9c01904ff

**Comment by yuki24** [comment]
confirmed https://github.com/kaminari/kaminari/commit/4536cc2800a40fcd91c0f4678133e4e9c01904ff broke integration with mongoid 4.0.

**Comment by yuki24** [comment]
This issue has been fixed by https://github.com/kaminari/kaminari/commit/d38c6849e02bb57289a3c6e7db062d9746d0aa4c. We'll cut a new release in a few weeks. Thanks!

**Comment by rdunlop** [comment]
Hi @yuki24 did a new release get cut?

**Comment by yuki24** [comment]
@rdunlop No not yet.

**Comment by joe1chen** [comment]
+1 Just ran into this bug. Any chance you can cut a new release?

**Comment by nchatu** [comment]
+1 ran into this bug. 

mongoid (4.0.2)
kaminari-mongoid (1.0.1)
rails (4.1.1)
ruby (2.2.0)
